routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'IndexController@index');
    //Kelas CRUD
    Route::get('/kelas', 'KelasController@index')->name('kelas');
   // Route::get('/kelas/add' , 'KelasController@create');
    Route::post('/kelas' , 'KelasController@store');
   // Route::get('kelas/{id}/edit','KelasController@edit');
    Route::put('/kelas','KelasController@update');
    Route::get('kelas/{id}/hapus','KelasController@delete');
    Route::get('kelas/cetak','KelasController@cetak')->name('cetak-kelas');
    //SPP CRUD
    Route::get('/spp', 'SPPController@index')->name('spp');
    //Route::get('/spp/add' , 'SPPController@create');
    Route::post('/spp' , 'SPPController@store');
    //Route::get('spp/{id}/edit','SPPController@edit');
    Route::put('/spp','SPPController@update');
    Route::get('spp/{id}/hapus','SPPController@delete');
    //Petugas CRUD
    Route::get('/petugas', 'PetugasController@index')->name('petugas');
    //Route::get('/petugas/add' , 'PetugasController@create');
    Route::post('/petugas' , 'PetugasController@store');
    //Route::get('petugas/{id}/edit','PetugasController@edit');
    Route::put('/petugas','PetugasController@update');
    Route::get('petugas/{id}/hapus', 'PetugasController@delete');
    //Siswa CRUD
    Route::get('/siswa', 'SiswaController@index')->name('siswa');
    //Route::get('/siswa/add' , 'SiswaController@create');
    Route::post('/siswa' , 'SiswaController@store');
    //Route::get('siswa/{id}/edit','SiswaController@edit');
    Route::put('/siswa','SiswaController@update');
    Route::get('siswa/{id}/hapus', 'SiswaController@delete');

    //Pembayaran
    Route::get('/pembayaran', 'SiswaController@pilihsiswa')->name('pembayaran');
    Route::get('pembayaran/add' , 'PembayaranController@create');
    Route::post('pembayaran/add' , 'PembayaranController@store');
    Route::get('siswa/{id}/edit','SiswaController@edit');
    Route::put('siswa/{id}/edit','SiswaController@update');
    Route::get('siswa/{id}/hapus', 'SiswaController@delete');

    //Transaksi
    Route::get('/transaksi', 'TransactionController@index');
    Route::post('/transaksi', 'TransactionController@store');

    //Histori
    Route::get('/histori', 'TransactionController@histori');
    Route::get('/hs', 'TransactionController@histori');


});

app/Petugas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Petugas extends Model
{
    public $primaryKey = 'id_petugas';
    protected $table = 'petugas';
    protected $fillable = ['username','password','nama_petugas','level'];

    public function getLevelDisplayAttribute(){
        if(@$this->attributes['level']=='admin') return 'Admin';
        if(@$this->attributes['level']=='petugas') return 'Petugas';
        return '-';
    }
}

resources/views/histori.blade.php
@extends('tmplt/header')

@section('content')
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Riwayat Pembayaran</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table text-gray-800" id="dthistori" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>#</th>
                <th>Nama Siswa</th>
                <th>Kelas</th>
                <th>Tanggal Bayar</th>
                <th>Bulan diBayar</th>
                <th>Tahun diBayar</th>
                <th>Jumlah Bayar</th>
                {{-- <th>Action</th> --}}
            </tr>
            </thead>
            <tbody>
            @foreach ($histori as $row)
            <tr>
                <th scope="row">{{ !empty($i) ? ++$i : $i = 1 }}</th>
                <td>{{ $row->nama }}</td>
                <td>{{ $row->nama_kelas }}</td>
                <td>{{ $row->tgl_bayar }}</td>
                <td>{{ $row->bulan_dibayar }}</td>
                <td>{{ $row->tahun_dibayar }}</td>
                <td>{{ $row->jumlah_bayar }}</td>
                {{-- <td>
                    <button class="btn btn-primary">Detail</button>
                </td> --}}
            </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    </div>
</div>
@endsection
@push('script')
    <script>
        $('#dthistori').DataTable();
    </script>
@endpush

resources/views/hs.blade.php
@extends('tmplt/headersiswa')

@section('content')
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Riwayat Pembayaran</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table text-gray-800" id="dthistori" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>#</th>
                <th>Nama Siswa</th>
                <th>Kelas</th>
                <th>Tanggal Bayar</th>
                <th>Bulan diBayar</th>
                <th>Tahun diBayar</th>
                <th>Jumlah Bayar</th>
                {{-- <th>Action</th> --}}
            </tr>
            </thead>
            <tbody>
            @foreach ($histori as $row)
            <tr>
                <th scope="row">{{ !empty($i) ? ++$i : $i = 1 }}</th>
                <td>{{ $row->nama }}</td>
                <td>{{ $row->nama_kelas }}</td>
                <td>{{ $row->tgl_bayar }}</td>
                <td>{{ $row->bulan_dibayar }}</td>
                <td>{{ $row->tahun_dibayar }}</td>
                <td>{{ $row->jumlah_bayar }}</td>
                {{-- <td>
                    <button class="btn btn-primary">Detail</button>
                </td> --}}
            </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    </div>
</div>
@endsection
@push('script')
    <script>
        $('#dthistori').DataTable();
    </script>
@endpush

resources/views/index.blade.php
@extends('tmplt/header')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
      <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <!-- Content Row -->
    <div class="row">

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">User Petugas</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Petugas::count()}}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-user fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Pembayaran Masuk</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Pembayaran::count()}}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks</div>
                <div class="row no-gutters align-items-center">
                  <div class="col-auto">
                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                  </div>
                  <div class="col">
                    <div class="progress progress-sm mr-2">
                      <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-auto">
                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Pending Requests Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Requests</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-comments fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Content Row -->

    <div class="row">

      <!-- Area Chart -->
      <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          <div class="card-body">
            <div class="chart-area">
              <canvas id="myAreaChart"></canvas>
            </div>
          </div>
        </div>
      </div>

      <!-- Pie Chart -->
      <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          <div class="card-body">
            <div class="chart-pie pt-4 pb-2">
              <canvas id="myPieChart"></canvas>
            </div>
            <div class="mt-4 text-center small">
              <span class="mr-2">
                <i class="fas fa-circle text-primary"></i> Direct
              </span>
              <span class="mr-2">
                <i class="fas fa-circle text-success"></i> Social
              </span>
              <span class="mr-2">
                <i class="fas fa-circle text-info"></i> Referral
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Content Row -->
    <div class="row">

      <!-- Content Column -->
      <div class="col-lg-6 mb-4">

        <!-- Project Card Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Projects</h6>
          </div>
          <div class="card-body">
            <h4 class="small font-weight-bold">Server Migration <span class="float-right">20%</span></h4>
            <div class="progress mb-4">
              <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <h4 class="small font-weight-bold">Sales Tracking <span class="float-right">40%</span></h4>
            <div class="progress mb-4">
              <div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <h4 class="small font-weight-bold">Customer Database <span class="float-right">60%</span></h4>
            <div class="progress mb-4">
              <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <h4 class="small font-weight-bold">Payout Details <span class="float-right">80%</span></h4>
            <div class="progress mb-4">
              <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <h4 class="small font-weight-bold">Account Setup <span class="float-right">Complete!</span></h4>
            <div class="progress">
              <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>

        <!-- Color System -->
        <div class="row">
          <div class="col-lg-6 mb-4">
            <div class="card bg-primary text-white shadow">
              <div class="card-body">
                Primary
                <div class="text-white-50 small">#4e73df</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <div class="card bg-success text-white shadow">
              <div class="card-body">
                Success
                <div class="text-white-50 small">#1cc88a</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <div class="card bg-info text-white shadow">
              <div class="card-body">
                Info
                <div class="text-white-50 small">#36b9cc</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <div class="card bg-warning text-white shadow">
              <div class="card-body">
                Warning
                <div class="text-white-50 small">#f6c23e</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <div class="card bg-danger text-white shadow">
              <div class="card-body">
                Danger
                <div class="text-white-50 small">#e74a3b</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <div class="card bg-secondary text-white shadow">
              <div class="card-body">
                Secondary
                <div class="text-white-50 small">#858796</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <div class="card bg-light text-black shadow">
              <div class="card-body">
                Light
                <div class="text-black-50 small">#f8f9fc</div>
              </div>
            </div>
        </div>
        <div class="col-lg-6 mb-4">
          <div class="card bg-dark text-white shadow">
            <div class="card-body">
                Dark
                <div class="text-white-50 small">#5a5c69</div>
            </div>
          </div>
        </div>
      </div>

      </div>

      <div class="col-lg-6 mb-4">

        <!-- Illustrations -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
          </div>
          <div class="card-body">
            <div class="text-center">
              <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="img/undraw_posting_photo.svg" alt="">
            </div>
            <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
            <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw &rarr;</a>
          </div>
        </div>

        <!-- Approach -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
          </div>
          <div class="card-body">
            <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>
            <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>
          </div>
        </div>

      </div>
    </div>
@endsection

resources/views/indexsiswa.blade.php
@extends('tmplt/headersiswa')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Dashboard Siswa</h1>
      {{-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> --}}
    </div>

    <!-- Content Row -->

@endsection

resources/views/kelas.blade.php
@extends('tmplt/header')

@section('content')
<!-- DataTales Example -->
@include('tmplt.feedback')
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Data Kelas</h6>
        <span class="d-sm-inline-block">

            <a href="#add" data-toggle="modal" data-target="#formModal" data-mode="add"  class="btn btn-sm btn-success shadow-sm"><i class="fa fa-plus"></i> Tambah</a>
            <a href="{{route('cetak-kelas')}}" class="btn btn-sm btn-secondary shadow-sm"><i class="fa fa-download"></i> Cetak</a> 
        </span>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table text-gray-800" id="dtkelas" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>#</th>
                <th>Nama Kelas</th>
                <th>Kompetensi Keahlian</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($colec as $row)
            <tr>
                <th scope="row">{{ !empty($i) ? ++$i : $i = 1 }}</th>
                <td>{{ $row->nama_kelas }}</td>
                <td>{{ $row->kompetensi_keahlian }}</td>
                <td>
                    <a href="#" data-toggle="modal" data-target="#formModal" data-mode="edit" data-id="{{$row->id_kelas}}" data-nama="{{$row->nama_kelas}}" data-komp="{{$row->kompetensi_keahlian}}" class="btn btn-sm btn-warning"><i class='fa fa-edit'></i></a>

                    <a href="#edit" data-toggle="modal" data-target="#confModal" data-nama="{{$row->nama_kelas}}" data-id="{{$row->id_kelas}}" class="btn btn-sm btn-danger" ><i class='fa fa-trash'></i></a>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    </div>
</div>
@endsection
@include('kelas/form')
@push('script')
<script>
    $(function(){
        $('#dtkelas').DataTable();
        $('#formModal').on('show.bs.modal', function(event){
            var button = $(event.relatedTarget);
            var id = button.data('id');
            var mode = button.data('mode');
            var nama = button.data('nama');
            var komp = button.data('komp');
            var modal = $(this);
            if(mode=='edit'){
                modal.find('.modal-title').text('Edit Data Kelas');
                modal.find('.modal-body #inputNama').val(nama);
                modal.find('.modal-body #inputKomp').val(komp);
                modal.find('.modal-body #method').html('{{method_field("PUT")}}<input type="hidden" name="id_kelas" value="'+id+'">');

            }
            else{
                modal.find('.modal-title').text('Tambah Data Kelas');
                modal.find('.modal-body #inputNama').val('');
                modal.find('.modal-body #inputKomp').val('');
                modal.find('.modal-body #method').html('');

            }
        });
    })

    $(function(){
        $('#confModal').on('show.bs.modal', function(event){
            var button = $(event.relatedTarget);
            var id = button.data('id');
            var nama = button.data('nama');
            var modal = $(this);
            modal.find('.modal-footer #btnHapus').html('<a href="kelas/'+id+'/hapus" type="submit" id="btnHapus" class="btn btn-danger">Delete</a>');
            modal.find('.modal-body #dataHapus').text(nama);
            });
    })
</script>

@endpush

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login</title>

  <!-- Custom fonts for this template-->
  <link href="{{asset('assets')}}/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
    <link href="{{asset('assets')}}/css/sb-admin-2.min.css" rel="stylesheet">
    @stack('stylelogin')

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class=" border-0 shadow-lg my-5">@include('tmplt.feedback')</div>
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                    <form class="user" action="{{url('login')}}" method="POST">
                        {{ csrf_field() }}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="username" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      Login
                    </button>
                    <hr>
                    <a href="index.html" class="btn btn-success btn-user btn-block">
                      <i class=""></i>Create an Account!
                    </a>
                    <a href="index.html" class="btn btn-danger btn-user btn-block">
                      <i class=""></i> Forgot Password?
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html"></a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="register.html"></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{asset('assets')}}/vendor/jquery/jquery.min.js"></script>
  <script src="{{asset('assets')}}/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{asset('assets')}}/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{asset('assets')}}/js/sb-admin-2.min.js"></script>

</body>

</html>

resources/views/petugas.blade.php
@extends('tmplt/header')

@section('content')
@include('tmplt.feedback')
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Data Petugas</h6>
        <a href="#add" data-toggle="modal" data-target="#formModal" data-mode="add" class="d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fa fa-plus"></i> Tambah</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table text-gray-800" id="dtpetugas" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>#</th>
                <th>Username</th>
                <th>Nama Petugas</th>
                <th>Level</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($petugas as $org)
            <tr>
                <th scope="row">{{ !empty($i) ? ++$i : $i = 1 }}</th>
                <td>{{ $org->username }}</td>
                <td>{{ $org->nama_petugas }}</td>
                <td>{{ $org->level_display }}</td>
                <td>
                    <a href="#" data-toggle="modal" data-target="#formModal" data-mode="edit" data-id="{{$org->id_petugas}}"
                        data-user="{{$org->username}}" data-pass="{{$org->password}}" data-level="{{$org->level}}"
                        data-nama="{{$org->nama_petugas}}" class="btn btn-sm btn-warning"><i class='fa fa-edit'></i></a>
                    <a href="#edit"  data-toggle="modal" data-target="#confModal" data-mode="edit" data-id="{{$org->id_petugas}}" data-nama="{{$org->nama_petugas}}"  class="btn btn-sm btn-danger"><i class='fa fa-trash'></i></a>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

        </div>
    </div>
</div>
@endsection
@include('petugas/form')
@push('script')
<script>
    $(function(){
        $('#dtpetugas').DataTable();
        $('#formModal').on('show.bs.modal', function(event){
            var button = $(event.relatedTarget);
            var id = button.data('id');
            var mode = button.data('mode');
            var user = button.data('user');
            var pass = button.data('pass');
            var lvl = button.data('level');
            var nama = button.data('nama');
            var modal = $(this);
            if(mode=='edit'){
                modal.find('.modal-title').text('Edit Data Petugas');
                modal.find('.modal-body #inputNama').val(nama);
                modal.find('.modal-body #inputUser').val(user);
                modal.find('.modal-body #inputLevel').val(lvl);
                modal.find('.modal-body #method').html('{{method_field("PUT")}}<input type="hidden" name="id_petugas" value="'+id+'">');

            }
            else{
                modal.find('.modal-title').text('Tambah Data Petugas');
                modal.find('.modal-body #inputNama').val('');
                modal.find('.modal-body #inputUser').val('');
                modal.find('.modal-body #inputLevel').val('');
                modal.find('.modal-body #method').html('');

            }
        });
    })

    $(function(){
        $('#confModal').on('show.bs.modal', function(event){
            var button = $(event.relatedTarget);
            var id = button.data('id');
            var tahun = button.data('nama');
            var modal = $(this);
            modal.find('.modal-footer #btnHapus').html('<a href="petugas/'+id+'/hapus" type="submit" id="btnHapus" class="btn btn-danger">Delete</a>');
            modal.find('.modal-body #dataHapus').text(tahun);
            });
    })
</script>

@endpush